all:
  hosts: {}
  children:
    webservers:
      vars:
        webserver: tomcat8
      hosts:
        MiMaquina:
          ansible_host: localhost
        tomcat[1:50].prod.itnow.es:
          webserver: tomcat9
    databases: {}
    
    
    
    
#ansible.connection=ssh|winrm       
#ansible_host=IP o NOMBRE del host
#ansible_port
#ansible_user
#ansible_password
#ansible_ssh_private_key_file
#ansible_become
